/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visão;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modeloBeansX.BeansEstoque;
import modeloBeansX.ModeloTabelaX;
import modeloConnectionX.ConectaBDX;
import modeloDaoX.DaoEstoque;

/**
 *
 * @author danie
 */
public class CadProdutos extends javax.swing.JFrame {

    /**
     * Creates new form CadProdutos
     */
    int flag = 0;
    BeansEstoque beansEstoque = new BeansEstoque();
    BeansEstoque _beansEstoque = new BeansEstoque();
    DaoEstoque daoEstoque = new DaoEstoque();
    ConectaBDX conexaoBD = new ConectaBDX();
    String permissao;
    String user;
    String nome;

    public CadProdutos() {
        initComponents();
        jTextFieldIDProduto.setVisible(false);
        preencherTabelaProdutos("select * from estoque order by categoria desc");
        jButtonCancelarProduto.setBackground(new Color(0, 0, 0, 0));
        jButtonEditarProduto.setBackground(new Color(0, 0, 0, 0));
        jButtonExcluirProduto.setBackground(new Color(0, 0, 0, 0));
        jButtonSalvarProduto.setBackground(new Color(0, 0, 0, 0));
        jComboBoxCategoriaProduto.setBackground(new Color(0, 0, 0, 0));
        jPanel1.setBackground(new Color(0, 0, 0, 0));
        jRadioButton1.setBackground(new Color(0, 0, 0, 0));
        jSpinnerQuantidadeProduto.setBackground(new Color(0, 0, 0, 0));
        jTextFieldFornecedor.setBackground(new Color(0, 0, 0, 0));
        jTextFieldIDProduto.setBackground(new Color(0, 0, 0, 0));
        jTextFieldNomeProduto.setBackground(new Color(0, 0, 0, 0));
        jTextFieldValorCompraProduto.setBackground(new Color(0, 0, 0, 0));
        jTextFieldValorVendaProduto.setBackground(new Color(0, 0, 0, 0));
        jButtonSair.setBackground(new Color(0, 0, 0, 0));
        
        
        URL url = this.getClass().getResource("/imagens/logoSafNormal.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(iconeTitulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButtonEditarProduto = new javax.swing.JButton();
        jButtonSalvarProduto = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jButtonNovo = new javax.swing.JButton();
        jTextFieldIDProduto = new javax.swing.JTextField();
        jButtonExcluirProduto = new javax.swing.JButton();
        jButtonCancelarProduto = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jTableProduto = new javax.swing.JTable();
        jTextFieldNomeProduto = new javax.swing.JTextField();
        jTextFieldValorCompraProduto = new javax.swing.JTextField();
        jTextFieldValorVendaProduto = new javax.swing.JTextField();
        jButtonPesquisarProduto = new javax.swing.JButton();
        jSpinnerQuantidadeProduto = new javax.swing.JSpinner();
        jTextFieldFornecedor = new javax.swing.JTextField();
        jComboBoxCategoriaProduto = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Produtos");
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1050, 610));
        setSize(new java.awt.Dimension(1050, 610));
        getContentPane().setLayout(null);

        jButtonEditarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botoes/botaoEditarNormal.png"))); // NOI18N
        jButtonEditarProduto.setEnabled(false);
        jButtonEditarProduto.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botoes/botaoEditar.png"))); // NOI18N
        jButtonEditarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditarProduto);
        jButtonEditarProduto.setBounds(900, 450, 120, 40);

        jButtonSalvarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botoes/botaoSalvarNormal.png"))); // NOI18N
        jButtonSalvarProduto.setEnabled(false);
        jButtonSalvarProduto.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botoes/botaoSalvar.png"))); // NOI18N
        jButtonSalvarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvarProduto);
        jButtonSalvarProduto.setBounds(900, 527, 120, 30);

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botoes/Botao Minimizar.png"))); // NOI18N
        jButtonSair.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botoes/Botao Minimizar Alterado.png"))); // NOI18N
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(980, 20, 40, 50);

        jButtonNovo.setText("NOVO");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNovo);
        jButtonNovo.setBounds(900, 370, 120, 40);

        jTextFieldIDProduto.setEditable(false);
        jTextFieldIDProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldIDProduto);
        jTextFieldIDProduto.setBounds(780, 20, 26, 20);

        jButtonExcluirProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botoes/botaoExcluirNormal.png"))); // NOI18N
        jButtonExcluirProduto.setEnabled(false);
        jButtonExcluirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluirProduto);
        jButtonExcluirProduto.setBounds(900, 410, 120, 40);

        jButtonCancelarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botoes/botaoCancelarNormal.png"))); // NOI18N
        jButtonCancelarProduto.setEnabled(false);
        jButtonCancelarProduto.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botoes/botaoCancelar.png"))); // NOI18N
        jButtonCancelarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelarProduto);
        jButtonCancelarProduto.setBounds(900, 493, 120, 30);

        jRadioButton1.setBorder(null);
        jRadioButton1.setEnabled(false);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(630, 410, 30, 20);

        jTableProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProdutoMouseClicked(evt);
            }
        });
        getContentPane().add(jTableProduto);
        jTableProduto.setBounds(40, 220, 820, 160);

        jTextFieldNomeProduto.setBorder(null);
        jTextFieldNomeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNomeProduto);
        jTextFieldNomeProduto.setBounds(110, 120, 600, 20);

        jTextFieldValorCompraProduto.setBorder(null);
        jTextFieldValorCompraProduto.setEnabled(false);
        getContentPane().add(jTextFieldValorCompraProduto);
        jTextFieldValorCompraProduto.setBounds(200, 150, 200, 30);

        jTextFieldValorVendaProduto.setBorder(null);
        jTextFieldValorVendaProduto.setEnabled(false);
        getContentPane().add(jTextFieldValorVendaProduto);
        jTextFieldValorVendaProduto.setBounds(640, 160, 200, 20);

        jButtonPesquisarProduto.setText("PESQUISAR");
        jButtonPesquisarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPesquisarProduto);
        jButtonPesquisarProduto.setBounds(720, 120, 110, 23);

        jSpinnerQuantidadeProduto.setModel(new javax.swing.SpinnerNumberModel());
        jSpinnerQuantidadeProduto.setBorder(null);
        jSpinnerQuantidadeProduto.setEnabled(false);
        getContentPane().add(jSpinnerQuantidadeProduto);
        jSpinnerQuantidadeProduto.setBounds(160, 410, 70, 30);

        jTextFieldFornecedor.setBorder(null);
        jTextFieldFornecedor.setEnabled(false);
        jTextFieldFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFornecedorActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldFornecedor);
        jTextFieldFornecedor.setBounds(170, 450, 230, 30);

        jComboBoxCategoriaProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "Remédio", "Cosmético" }));
        jComboBoxCategoriaProduto.setBorder(null);
        jComboBoxCategoriaProduto.setEnabled(false);
        jComboBoxCategoriaProduto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxCategoriaProdutoItemStateChanged(evt);
            }
        });
        jComboBoxCategoriaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoriaProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxCategoriaProduto);
        jComboBoxCategoriaProduto.setBounds(172, 490, 220, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/telaProduto.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1050, 610);

        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(410, 150, 0, 0);

        setLocation(new java.awt.Point(280, 90));
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxCategoriaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoriaProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCategoriaProdutoActionPerformed

    private void jTextFieldNomeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeProdutoActionPerformed

    private void jTextFieldFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFornecedorActionPerformed

    private void jButtonCancelarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarProdutoActionPerformed
        // TODO add your handling code here:
        //ATIVADORES
        //BOTÕES
        jButtonNovo.setEnabled(true);
        jButtonPesquisarProduto.setEnabled(true);
        //CAMPOS DE TEXTO
        jTextFieldValorCompraProduto.setEditable(true);
        jTextFieldValorVendaProduto.setEditable(true);
        jTextFieldFornecedor.setEditable(true);
        jComboBoxCategoriaProduto.setEditable(true);

        //DESATIVADORES
        //CAMPOS DE TEXTO
        jTextFieldValorCompraProduto.setEnabled(false);
        jTextFieldValorVendaProduto.setEnabled(false);
        jSpinnerQuantidadeProduto.setEnabled(false);
        jTextFieldFornecedor.setEnabled(false);
        jComboBoxCategoriaProduto.setEnabled(false);
        //BOTÕES
        jButtonSalvarProduto.setEnabled(false);
        jButtonCancelarProduto.setEnabled(false);
        jButtonEditarProduto.setEnabled(false);
        jButtonExcluirProduto.setEnabled(false);

        //SETERES DE TEXTO
        jTextFieldNomeProduto.setText(null);
        jTextFieldValorCompraProduto.setText(null);
        jTextFieldValorVendaProduto.setText(null);
        jSpinnerQuantidadeProduto.setValue(0);
        jTextFieldFornecedor.setText(null);
        jComboBoxCategoriaProduto.setSelectedIndex(0);
        jRadioButton1.setSelected(false);

        preencherTabelaProdutos("select * from estoque order by categoria desc");

    }//GEN-LAST:event_jButtonCancelarProdutoActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        // TODO add your handling code here
        flag = 1;
        //ATIVADORES
        //CAMPOS DE TEXTO
        jTextFieldValorCompraProduto.setEnabled(true);
        jTextFieldValorVendaProduto.setEnabled(true);
        jSpinnerQuantidadeProduto.setEnabled(true);
        jTextFieldFornecedor.setEnabled(true);
        jComboBoxCategoriaProduto.setEnabled(true);

        //BOTÕES
        jButtonSalvarProduto.setEnabled(true);
        jButtonCancelarProduto.setEnabled(true);

        //DESATIVADORES
        jButtonNovo.setEnabled(false);
        jButtonPesquisarProduto.setEnabled(false);

    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonEditarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarProdutoActionPerformed
        // TODO add your handling code here:
        flag = 2;
        //ATIVADORES
        //EDIÇÃO DOS CAMPOS DE TEXTO
        jTextFieldValorCompraProduto.setEditable(true);
        jTextFieldValorVendaProduto.setEditable(true);
        jTextFieldFornecedor.setEditable(true);
        jComboBoxCategoriaProduto.setEditable(true);
        //BOTÕES
        jButtonSalvarProduto.setEnabled(true);
    }//GEN-LAST:event_jButtonEditarProdutoActionPerformed

    private void jButtonSalvarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarProdutoActionPerformed
        // TODO add your handling code here:
        if (flag == 1) {
            if (jTextFieldNomeProduto.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Por favor, insira o nome do produto.");
            } else if (jTextFieldValorCompraProduto.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Por favor, insira o valor de compra do produto.");
            } else if (jTextFieldValorVendaProduto.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Por favor, insira o valor de venda do produto.");
            } else if (jTextFieldFornecedor.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Por favor, insira o fornecedor do produto.");
            } else if (jComboBoxCategoriaProduto.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(null, "Por favor, escolha uma categoria pro produto.");
            } else {
                //beansEstoque.setIdproduto(Integer.parseInt(jTextFieldIDProduto.getText()));
                beansEstoque.setNomeproduto(jTextFieldNomeProduto.getText());
                beansEstoque.setValorcompra(Double.parseDouble(jTextFieldValorCompraProduto.getText()));
                beansEstoque.setValorvenda(Double.parseDouble(jTextFieldValorVendaProduto.getText()));
                beansEstoque.setQuantidade((int) jSpinnerQuantidadeProduto.getValue());
                beansEstoque.setFornecedor(jTextFieldFornecedor.getText());
                beansEstoque.setCategoria((String) jComboBoxCategoriaProduto.getSelectedItem());
                if (jRadioButton1.isSelected() && jComboBoxCategoriaProduto.getSelectedItem().equals("Remédio")) {
                    beansEstoque.setReceita("Sim");
                } else if (!jRadioButton1.isSelected() && jComboBoxCategoriaProduto.getSelectedItem().equals("Remédio")) {
                    beansEstoque.setReceita("Não");
                }

                int teste = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja salvar este produto?", "Atenção!", 0, 0);
                if (teste == JOptionPane.YES_OPTION) {
                    daoEstoque.salvar(beansEstoque);
                    jButtonCancelarProduto.doClick();
                }
            }
        } else { //Se a flag for 2 (editar)
            if (jTextFieldNomeProduto.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Por favor, insira o nome do produto.");
            } else if (jTextFieldValorCompraProduto.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Por favor, insira o valor de compra do produto.");
            } else if (jTextFieldValorVendaProduto.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Por favor, insira o valor de venda do produto.");
            } else if (jTextFieldFornecedor.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Por favor, insira o fornecedor do produto.");
            } else if (jComboBoxCategoriaProduto.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(null, "Por favor, escolha uma categoria pro produto.");
            } else {
                beansEstoque.setIdproduto(Integer.parseInt(jTextFieldIDProduto.getText()));
                beansEstoque.setNomeproduto(jTextFieldNomeProduto.getText());
                beansEstoque.setValorcompra(Double.parseDouble(jTextFieldValorCompraProduto.getText()));
                beansEstoque.setValorvenda(Double.parseDouble(jTextFieldValorVendaProduto.getText()));
                beansEstoque.setQuantidade((int) jSpinnerQuantidadeProduto.getValue());
                beansEstoque.setFornecedor(jTextFieldFornecedor.getText());
                beansEstoque.setCategoria((String) jComboBoxCategoriaProduto.getSelectedItem());
                if (jRadioButton1.isSelected() && jComboBoxCategoriaProduto.getSelectedItem().equals("Remédio")) {
                    beansEstoque.setReceita("Sim");
                } else if (!jRadioButton1.isSelected() && jComboBoxCategoriaProduto.getSelectedItem().equals("Remédio")) {
                    beansEstoque.setReceita("Não");
                }

                int teste = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja editar este produto?", "Atenção!", 0, 0);
                if (teste == JOptionPane.YES_OPTION) {
                    daoEstoque.editar(beansEstoque);
                    jButtonCancelarProduto.doClick();
                }
            }
        }
    }//GEN-LAST:event_jButtonSalvarProdutoActionPerformed

    private void jButtonPesquisarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarProdutoActionPerformed
        // TODO add your handling code here:
        //ATIVADORES
        //CAMPOS DE TEXTO
        jTextFieldValorCompraProduto.setEnabled(true);
        jTextFieldValorVendaProduto.setEnabled(true);
        jSpinnerQuantidadeProduto.setEnabled(true);
        jTextFieldFornecedor.setEnabled(true);
        jComboBoxCategoriaProduto.setEnabled(true);
        //BOTÕES
        jButtonCancelarProduto.setEnabled(true);
        jButtonEditarProduto.setEnabled(true);
        jButtonExcluirProduto.setEnabled(true);

        //DESATIVADORES
        //EDIÇÃO DOS CAMPOS DE TEXTO
        jTextFieldValorCompraProduto.setEditable(false);
        jTextFieldValorVendaProduto.setEditable(false);
        jTextFieldFornecedor.setEditable(false);
        jComboBoxCategoriaProduto.setEditable(false);
        //BOTÕES
        jButtonNovo.setEnabled(false);
        jButtonSalvarProduto.setEnabled(false);

        beansEstoque.setPesquisa(jTextFieldNomeProduto.getText());
        _beansEstoque = daoEstoque.buscaEstoque(beansEstoque);
        jTextFieldIDProduto.setText(Integer.toString(_beansEstoque.getIdproduto()));
        jTextFieldNomeProduto.setText(_beansEstoque.getNomeproduto());
        jTextFieldValorCompraProduto.setText(Double.toString(_beansEstoque.getValorcompra()));
        jTextFieldValorVendaProduto.setText(Double.toString(_beansEstoque.getValorvenda()));
        jSpinnerQuantidadeProduto.setValue(_beansEstoque.getQuantidade());
        jTextFieldFornecedor.setText(_beansEstoque.getFornecedor());
        jComboBoxCategoriaProduto.setSelectedItem(_beansEstoque.getCategoria());
        if (_beansEstoque.getReceita().equals("Sim")) {
            jRadioButton1.setSelected(true);
        } else {
            jRadioButton1.setSelected(false);
        }
    }//GEN-LAST:event_jButtonPesquisarProdutoActionPerformed

    private void jButtonExcluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirProdutoActionPerformed
        // TODO add your handling code here:
        int teste = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir este produto?", "Atenção!", 0, 0);
        if (teste == JOptionPane.YES_OPTION) {
            beansEstoque.setIdproduto(Integer.parseInt(jTextFieldIDProduto.getText()));
            daoEstoque.excluir(beansEstoque);
            jButtonCancelarProduto.doClick();
        } else {

        }
    }//GEN-LAST:event_jButtonExcluirProdutoActionPerformed

    private void jComboBoxCategoriaProdutoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxCategoriaProdutoItemStateChanged
        // TODO add your handling code here:
        if (jComboBoxCategoriaProduto.getSelectedIndex() == 2) {
            jRadioButton1.setEnabled(false);
            jRadioButton1.setSelected(false);
        } else if (jComboBoxCategoriaProduto.getSelectedIndex() == 1) {
            jRadioButton1.setEnabled(true);
        } else {
            jRadioButton1.setEnabled(false);
            jRadioButton1.setSelected(false);
        }
    }//GEN-LAST:event_jComboBoxCategoriaProdutoItemStateChanged

    private void jTableProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProdutoMouseClicked
        // TODO add your handling code here:
        String codigo = "" + jTableProduto.getValueAt(jTableProduto.getSelectedRow(), 0);

        // abre a conexao
        conexaoBD.conectaBD();
        // excuta um string sql
        conexaoBD.executaSql("select * from estoque where idproduto='" + codigo + "'");

        try {
            // pega o primeiro do banco
            conexaoBD.rs.first();
            jTextFieldIDProduto.setText(Integer.toString(conexaoBD.rs.getInt("idproduto")));
            jTextFieldNomeProduto.setText(conexaoBD.rs.getString("nomeproduto"));
            jTextFieldValorCompraProduto.setText(Double.toString(conexaoBD.rs.getDouble("valorcompra")));
            jTextFieldValorVendaProduto.setText(Double.toString(conexaoBD.rs.getDouble("valorvenda")));
            jSpinnerQuantidadeProduto.setValue(conexaoBD.rs.getInt("quantidade"));
            jTextFieldFornecedor.setText(conexaoBD.rs.getString("fornecedor"));
            jComboBoxCategoriaProduto.setSelectedItem(conexaoBD.rs.getString("categoria"));
            if (conexaoBD.rs.getString("receita").equals("Sim")) {
                jRadioButton1.setSelected(true);
            } else {
                jRadioButton1.setSelected(false);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao selecionar dados.\nErro: " + ex);
        }
        // fecha a conexão
        conexaoBD.desconectaBD();

        //ATIVADORES
        //CAMPOS DE TEXTO
        jTextFieldValorCompraProduto.setEnabled(true);
        jTextFieldValorVendaProduto.setEnabled(true);
        jSpinnerQuantidadeProduto.setEnabled(true);
        jTextFieldFornecedor.setEnabled(true);
        jComboBoxCategoriaProduto.setEnabled(true);
        //BOTÕES
        jButtonCancelarProduto.setEnabled(true);
        jButtonEditarProduto.setEnabled(true);
        jButtonExcluirProduto.setEnabled(true);

        //DESATIVADORES
        //EDIÇÃO DOS CAMPOS DE TEXTO
        jTextFieldValorCompraProduto.setEditable(false);
        jTextFieldValorVendaProduto.setEditable(false);
        jTextFieldFornecedor.setEditable(false);
        jComboBoxCategoriaProduto.setEditable(false);
        //BOTÕES
        jButtonNovo.setEnabled(false);
        jButtonSalvarProduto.setEnabled(false);


    }//GEN-LAST:event_jTableProdutoMouseClicked

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jTextFieldIDProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDProdutoActionPerformed
    public void preencherTabelaProdutos(String sql) {
        ArrayList dadosUsuario = new ArrayList();
        String colunas[] = new String[]{"ID", "Nome", "$ Compra", "$ Venda", "QTD", "Fornecedor", "Categoria", "Receita"};

        // abre a conexao
        conexaoBD.conectaBD();
        conexaoBD.executaSql(sql);

        try {
            // pega o primeiro resultado encontrado na tabela
            conexaoBD.rs.first();

            // mostra todos os dados da tabela
            do {
                dadosUsuario.add(new Object[]{
                    conexaoBD.rs.getInt("idproduto"),
                    conexaoBD.rs.getString("nomeproduto"),
                    conexaoBD.rs.getDouble("valorcompra"),
                    conexaoBD.rs.getDouble("valorvenda"),
                    conexaoBD.rs.getString("quantidade"),
                    conexaoBD.rs.getString("fornecedor"),
                    conexaoBD.rs.getString("categoria"),
                    conexaoBD.rs.getString("receita")

                });
            } while (conexaoBD.rs.next());// enquanto houver dados
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher ArrayList.\nErro: " + ex);
        }

// cria uma intancia do modelo de tabela aqui nos passamos todos os objetos e o título de cada uma das colunas
        ModeloTabelaX modeloTabela = new ModeloTabelaX(dadosUsuario, colunas);

        // seta o modelo da tabela 
        jTableProduto.setModel(modeloTabela);

        // ID
        jTableProduto.getColumnModel().getColumn(0).setPreferredWidth(30);
        jTableProduto.getColumnModel().getColumn(0).setResizable(false);

        // NOME
        jTableProduto.getColumnModel().getColumn(1).setPreferredWidth(85);
        jTableProduto.getColumnModel().getColumn(1).setResizable(false);

        // VALOR COMPRA
        jTableProduto.getColumnModel().getColumn(2).setPreferredWidth(70);
        jTableProduto.getColumnModel().getColumn(2).setResizable(false);

        // VALOR VENDA
        jTableProduto.getColumnModel().getColumn(3).setPreferredWidth(70);
        jTableProduto.getColumnModel().getColumn(3).setResizable(false);

        // QTD
        jTableProduto.getColumnModel().getColumn(4).setPreferredWidth(35);
        jTableProduto.getColumnModel().getColumn(4).setResizable(false);

        // FORNECEDOR
        jTableProduto.getColumnModel().getColumn(5).setPreferredWidth(120);
        jTableProduto.getColumnModel().getColumn(5).setResizable(false);

        // CATEGORIA
        jTableProduto.getColumnModel().getColumn(6).setPreferredWidth(85);
        jTableProduto.getColumnModel().getColumn(6).setResizable(false);

        // RECEITA
        jTableProduto.getColumnModel().getColumn(7).setPreferredWidth(55);
        jTableProduto.getColumnModel().getColumn(7).setResizable(false);

        // não deixa reordenar os dados da tabela
        jTableProduto.getTableHeader().setReorderingAllowed(false);

        // não deixa a tabela ser redimensionada
        jTableProduto.setAutoResizeMode(jTableProduto.AUTO_RESIZE_OFF);

        // permite selecionar apenas um dado na tabela por vez
        jTableProduto.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        // fecha a conexão
        conexaoBD.desconectaBD();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelarProduto;
    private javax.swing.JButton jButtonEditarProduto;
    private javax.swing.JButton jButtonExcluirProduto;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisarProduto;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSalvarProduto;
    private javax.swing.JComboBox<String> jComboBoxCategoriaProduto;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JSpinner jSpinnerQuantidadeProduto;
    private javax.swing.JTable jTableProduto;
    private javax.swing.JTextField jTextFieldFornecedor;
    private javax.swing.JTextField jTextFieldIDProduto;
    private javax.swing.JTextField jTextFieldNomeProduto;
    private javax.swing.JTextField jTextFieldValorCompraProduto;
    private javax.swing.JTextField jTextFieldValorVendaProduto;
    // End of variables declaration//GEN-END:variables
}
