/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visão;
import controleX.CriptografaSenha;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modeloBeansX.BeansUsuario;
import modeloBeansX.ModeloTabelaX;
import modeloConnectionX.ConectaBDX;
import modeloDaoX.DaoUsuario;
/**
 *
 * @author danie
 */
public class CadUsuario extends javax.swing.JFrame {
    BeansUsuario _beansUsuario = new BeansUsuario();
    BeansUsuario beansUsuario = new BeansUsuario();
    DaoUsuario daoUsuario = new DaoUsuario();
    ConectaBDX conexaoBD =  new ConectaBDX();
    int flag = 0;
    int charflag = 0;
    String permissao;
    String user;
    String nome;
    public CadUsuario(String user, String permissao, String nome) {
        
        initComponents();
        
        this.permissao = permissao;
        this.user = user;
        
        this.setResizable(false);
        
        URL url = this.getClass().getResource("/icones/addusuario16.png");  
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url); 
        this.setIconImage(iconeTitulo);
        
        preencherTabela("select * from usuarios order by usuario ");
    }

    CadUsuario() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jButtonSair = new javax.swing.JButton();
        jPanelBotoes = new javax.swing.JPanel();
        jButtonDel = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonNovo = new javax.swing.JButton();
        jPanelFormulario = new javax.swing.JPanel();
        jLabelUsuario = new javax.swing.JLabel();
        jButtonPesquisar = new javax.swing.JButton();
        jLabelSenha = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jComboBoxPermissao = new javax.swing.JComboBox<>();
        jLabelPermissão = new javax.swing.JLabel();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jButtonMostrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePesquisaUsuario = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Funcionários");
        getContentPane().setLayout(null);

        jLabelTitulo.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabelTitulo.setText("Administração de Usuários");
        getContentPane().add(jLabelTitulo);
        jLabelTitulo.setBounds(20, 10, 320, 34);

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(10, 400, 60, 30);

        jPanelBotoes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonDel.setText("Deletar");
        jButtonDel.setEnabled(false);
        jButtonDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDelActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBotoesLayout = new javax.swing.GroupLayout(jPanelBotoes);
        jPanelBotoes.setLayout(jPanelBotoesLayout);
        jPanelBotoesLayout.setHorizontalGroup(
            jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBotoesLayout.setVerticalGroup(
            jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButtonDel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelBotoes);
        jPanelBotoes.setBounds(10, 60, 130, 240);

        jPanelFormulario.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelUsuario.setText("Usuário");

        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jLabelSenha.setText("Senha");
        jLabelSenha.setEnabled(false);

        jTextFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioActionPerformed(evt);
            }
        });

        jComboBoxPermissao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diretor", "Gerente", "Farmacêutico", "Vendedor", "Perfumista", "Balconista" }));
        jComboBoxPermissao.setEnabled(false);
        jComboBoxPermissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPermissaoActionPerformed(evt);
            }
        });

        jLabelPermissão.setText("Permissão");
        jLabelPermissão.setEnabled(false);

        jPasswordFieldSenha.setEditable(false);
        jPasswordFieldSenha.setEnabled(false);

        jButtonMostrar.setText("Mostrar");
        jButtonMostrar.setEnabled(false);
        jButtonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFormularioLayout = new javax.swing.GroupLayout(jPanelFormulario);
        jPanelFormulario.setLayout(jPanelFormularioLayout);
        jPanelFormularioLayout.setHorizontalGroup(
            jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormularioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPermissão)
                    .addComponent(jComboBoxPermissao, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelFormularioLayout.createSequentialGroup()
                        .addGroup(jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPasswordFieldSenha, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                        .addGroup(jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelFormularioLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelFormularioLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jButtonMostrar))))
                    .addComponent(jLabelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 8, Short.MAX_VALUE))
        );
        jPanelFormularioLayout.setVerticalGroup(
            jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormularioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPermissão)
                .addGap(11, 11, 11)
                .addComponent(jComboBoxPermissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabelUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jLabelSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMostrar))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelFormulario);
        jPanelFormulario.setBounds(180, 60, 360, 240);

        jTablePesquisaUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePesquisaUsuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePesquisaUsuario);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(180, 322, 360, 120);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
     flag = 1;
     //Ativadores
     jButtonSalvar.setEnabled(true);
     jButtonCancelar.setEnabled(true);
     jButtonMostrar.setEnabled(true);
     jLabelUsuario.setEnabled(true);
     jLabelSenha.setEnabled(true);
     jLabelPermissão.setEnabled(true);
     jComboBoxPermissao.setEnabled(true);
     jPasswordFieldSenha.setEnabled(true);
     
     //Desativadores
     jButtonNovo.setEnabled(false);
     jButtonPesquisar.setEnabled(false);
     jButtonEditar.setEnabled(false);
     jButtonSair.setEnabled(false);
     //habilita os campos de texto após clicar no botão "novo"
     jTextFieldUsuario.setEnabled(true);  
     jPasswordFieldSenha.setEnabled(true);
     
     jTextFieldUsuario.setEditable(true);  
     jPasswordFieldSenha.setEditable(true);
     
    jScrollPane1.setEnabled(false);
    jTablePesquisaUsuario.setEnabled(false);
    jTablePesquisaUsuario.clearSelection();
     
     //limpar campos de texto

    jTextFieldUsuario.setText(null);
    jPasswordFieldSenha.setText(null);
    jComboBoxPermissao.setSelectedIndex(0);
        
        
    //coloca o foco no campo "código" após criar um novo cadastro
    jTextFieldUsuario.requestFocus();
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsuarioActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        //jTextField_Pesquisar.requestFocus();
        if(flag == 1){
            
            String senha = jPasswordFieldSenha.getText().trim();
            //quando o campo está em branco
            if(jTextFieldUsuario.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(null, "Insira um nome para prosseguir!", "Atenção!", 2);
                jTextFieldUsuario.requestFocus();
            }
            else if(jPasswordFieldSenha.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(null, "Insira uma senha para prosseguir!", "Atenção!", 2);
                jPasswordFieldSenha.requestFocus();
            }
            else{
                CriptografaSenha criptografaSenha = new CriptografaSenha();
                criptografaSenha.setSenha(senha);
                String senhaCriptografada = criptografaSenha.getSenha();
                beansUsuario.setUsuario(jTextFieldUsuario.getText());
                beansUsuario.setSenha(senhaCriptografada);
                beansUsuario.setPermissao(jComboBoxPermissao.getSelectedIndex());
                daoUsuario.salvar(beansUsuario);

                //Ativadores
                jButtonNovo.setEnabled(true);
                jButtonPesquisar.setEnabled(true);
                jButtonSair.setEnabled(true);
                jScrollPane1.setEnabled(true);
                jTablePesquisaUsuario.setEnabled(true);

                //Desativadores
                jButtonCancelar.setEnabled(false);
                jButtonEditar.setEnabled(false);
                jButtonDel.setEnabled(false);
                jButtonSalvar.setEnabled(false);
                jButtonMostrar.setEnabled(false);

                jPasswordFieldSenha.setEnabled(false);
                jComboBoxPermissao.setEnabled(false);

                jLabelSenha.setEnabled(false);
                jLabelPermissão.setEnabled(false);

                //Seteres de texto
                jTextFieldUsuario.setText(null);
                jPasswordFieldSenha.setText(null);
                jComboBoxPermissao.setSelectedIndex(0);
                preencherTabela("select * from usuarios order by usuario ");
            }
    }//GEN-LAST:event_jButtonSalvarActionPerformed
        else{
            String senha = jPasswordFieldSenha.getText().trim();
            CriptografaSenha criptografaSenha = new CriptografaSenha();
            criptografaSenha.setSenha(senha);
            String senhaCriptografada = criptografaSenha.getSenha();
            beansUsuario.setSenha(senhaCriptografada);
            beansUsuario.setUsuario(jTextFieldUsuario.getText());
            beansUsuario.setPermissao(jComboBoxPermissao.getSelectedIndex());
            
            int teste = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja editar os dados desse usuário? \n"+ "Permissão: "+ beansUsuario.getPermissao()+ "\n"+ "Usuário: "+ beansUsuario.getUsuario()+ "\n" +  "Atenção!");
            if(teste == 0){
                daoUsuario.editar(beansUsuario);

                //Ativadores
                jButtonNovo.setEnabled(true);
                jButtonPesquisar.setEnabled(true);
                jButtonSair.setEnabled(true);
                jScrollPane1.setEnabled(true);
                jTablePesquisaUsuario.setEnabled(true);

                //Desativadores
                jButtonCancelar.setEnabled(false);
                jButtonEditar.setEnabled(false);
                jButtonDel.setEnabled(false);
                jButtonSalvar.setEnabled(false);
                jButtonMostrar.setEnabled(false);

                jPasswordFieldSenha.setEnabled(false);
                jComboBoxPermissao.setEnabled(false);

                jLabelSenha.setEnabled(false);
                jLabelPermissão.setEnabled(false);
                
                //Seteres de texto
                jTextFieldUsuario.setText(null);
                jPasswordFieldSenha.setText(null);
                jComboBoxPermissao.setSelectedIndex(0);
                preencherTabela("select * from usuarios order by usuario ");
            }
        }
    }
    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed

    beansUsuario.setPesquisar(jTextFieldUsuario.getText());


    _beansUsuario.setUsuario("");
    _beansUsuario.setSenha("");
    _beansUsuario.setPermissao(1);

    _beansUsuario = daoUsuario.buscaUsuario(beansUsuario);

    //Seteres de texto
    jTextFieldUsuario.setText(_beansUsuario.getUsuario());
    jComboBoxPermissao.setSelectedItem(_beansUsuario.getPermissao());


    //Ativadores
    jTextFieldUsuario.setEnabled(true);
    jPasswordFieldSenha.setEnabled(true);
    jLabelUsuario.setEnabled(true);
    jLabelSenha.setEnabled(true);
    jLabelPermissão.setEnabled(true);
    jComboBoxPermissao.setEnabled(true);

    jButtonEditar.setEnabled(true);
    jButtonDel.setEnabled(true);
    jButtonCancelar.setEnabled(true);
    //Desativadores
    jButtonNovo.setEnabled(false);
    jButtonPesquisar.setEnabled(false);

    jTextFieldUsuario.setEditable(false);
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        //Ativadores
        jTextFieldUsuario.setEditable(true);
        jTextFieldUsuario.setEnabled(true);
        jButtonSair.setEnabled(true);

        jScrollPane1.setEnabled(true);
        jTablePesquisaUsuario.setEnabled(true);

        jButtonNovo.setEnabled(true);
        jButtonPesquisar.setEnabled(true);

        jLabelUsuario.setEnabled(true);

        //Desativadores
        jLabelSenha.setEnabled(false);
        jLabelPermissão.setEnabled(false);

        jPasswordFieldSenha.setEnabled(false);
        jComboBoxPermissao.setEnabled(false);

        jButtonSalvar.setEnabled(false);
        jButtonCancelar.setEnabled(false);
        jButtonEditar.setEnabled(false);
        jButtonDel.setEnabled(false);
        jButtonMostrar.setEnabled(false);


        //limpar campos de texto
        jTextFieldUsuario.setText(null);
        jPasswordFieldSenha.setText(null);
        jComboBoxPermissao.setSelectedIndex(0);

        preencherTabela("select * from usuarios order by usuario ");
        //coloca o foco no campo "nome" após cancelar
        jTextFieldUsuario.requestFocus();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed

        TelaPrincipal telaPrincipal = new TelaPrincipal(user, permissao, nome);
        telaPrincipal.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDelActionPerformed
        // TODO add your handling code here:
        beansUsuario.setUsuario(jTextFieldUsuario.getText());
        
        int teste = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir os dados desse usuário? \n"+ "Permissão: "+ beansUsuario.getPermissao()+ "\n"+ "Usuário: "+ beansUsuario.getUsuario()+ "\n" + "Atenção!");
        if(teste == 0){
            daoUsuario.excluir(beansUsuario);
            
            //Ativadores
            jButtonNovo.setEnabled(true);
            jButtonPesquisar.setEnabled(true);
            jTextFieldUsuario.setEditable(true);
            jButtonSair.setEnabled(true);
            
            //Desativadores
            jButtonCancelar.setEnabled(false);
            jButtonEditar.setEnabled(false);
            jButtonDel.setEnabled(false);
            jButtonMostrar.setEnabled(false);
            
            jPasswordFieldSenha.setEnabled(false);
            jComboBoxPermissao.setEnabled(false);
            
            jLabelSenha.setEnabled(false);
            jLabelPermissão.setEnabled(false);
            
            //Seteres de texto
            jTextFieldUsuario.setText(null);
            jPasswordFieldSenha.setText(null);
            jComboBoxPermissao.setSelectedIndex(0);

            preencherTabela("select * from usuarios order by usuario ");
        }
    }//GEN-LAST:event_jButtonDelActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // TODO add your handling code here:
        flag = 2;
        
        //Ativadores
        
        jTextFieldUsuario.setEditable(true);
        jPasswordFieldSenha.setEditable(true);
        jTextFieldUsuario.setEnabled(true);
        jPasswordFieldSenha.setEnabled(true);
        jComboBoxPermissao.setEnabled(true);
        
        jLabelPermissão.setEnabled(true);
        jLabelSenha.setEnabled(true);
        jLabelUsuario.setEnabled(true);
        
        jButtonSalvar.setEnabled(true);
        jButtonMostrar.setEnabled(true);
                
        
        jTextFieldUsuario.requestFocus();
        
        //Desativadores
        jButtonPesquisar.setEnabled(false);
        jButtonNovo.setEnabled(false);
        jButtonDel.setEnabled(false);
        jButtonEditar.setEnabled(false);
        jScrollPane1.setEnabled(false);
        jTablePesquisaUsuario.setEnabled(false);
        jTablePesquisaUsuario.clearSelection();
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jTablePesquisaUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePesquisaUsuarioMouseClicked
        String usuario = "" + jTablePesquisaUsuario.getValueAt(jTablePesquisaUsuario.getSelectedRow(), 0);
        
        // abre a conexao
        conexaoBD.conectaBD();        
        // excuta um string sql
        conexaoBD.executaSql("select * from usuarios where usuario='" + usuario+ "'");
        
        try {
            // pega o primeiro do banco
            conexaoBD.rs.first();
            jTextFieldUsuario.setText(conexaoBD.rs.getString("usuario"));
            jComboBoxPermissao.setSelectedIndex(conexaoBD.rs.getInt("permissao"));
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao selecionar dados.\nErro: " + ex);
        }        
        // fecha a conexão
        conexaoBD.desconectaBD();
        
        // libera botões 
        jButtonEditar.setEnabled(true);
        jButtonDel.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        
        // bloqueia botão
        jButtonSair.setEnabled(false);
    }
        public void preencherTabela(String sql){
        ArrayList dadosUsuario = new ArrayList();
        String colunas[] = new String[]{"Nome", "Permissão"};
        
        // abre a conexao
        conexaoBD.conectaBD();
        conexaoBD.executaSql(sql);
        
        try {            
            // pega o primeiro resultado encontrado na tabela
            conexaoBD.rs.first();
            
            // mostra todos os dados da tabela
            do{
                dadosUsuario.add(new Object[]{
                    conexaoBD.rs.getString("usuario"),
                    conexaoBD.rs.getInt("permissao"),                  
                    
                });
            }while(conexaoBD.rs.next());// enquanto houver dados
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher ArrayList.\nErro: " + ex);
        }
        
// cria uma intancia do modelo de tabela aqui nos passamos todos os objetos e o título de cada uma das colunas
        ModeloTabelaX modeloTabela = new ModeloTabelaX(dadosUsuario, colunas);
        
        // seta o modelo da tabela 
        jTablePesquisaUsuario.setModel(modeloTabela);
        
        // dados do Nome do usario
        jTablePesquisaUsuario.getColumnModel().getColumn(0).setPreferredWidth(250);
        jTablePesquisaUsuario.getColumnModel().getColumn(0).setResizable(false);
        
        // dados da permissao do usuario
        jTablePesquisaUsuario.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTablePesquisaUsuario.getColumnModel().getColumn(1).setResizable(false);
        
        // não deixa reordenar os dados da tabela
        jTablePesquisaUsuario.getTableHeader().setReorderingAllowed(false);
        
        // não deixa a tabela ser redimensionada
        jTablePesquisaUsuario.setAutoResizeMode(jTablePesquisaUsuario.AUTO_RESIZE_OFF);
        
        // permite selecionar apenas um dado na tabela por vez
        jTablePesquisaUsuario.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        // fecha a conexão
        conexaoBD.desconectaBD();
        
    }//GEN-LAST:event_jTablePesquisaUsuarioMouseClicked

    private void jComboBoxPermissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPermissaoActionPerformed
    }//GEN-LAST:event_jComboBoxPermissaoActionPerformed

    private void jButtonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarActionPerformed
        // TODO add your handling code here:
        if(charflag == 1){
            jPasswordFieldSenha.setEchoChar('*');
            charflag = 0;
        }
        else{
            jPasswordFieldSenha.setEchoChar((char)0);
            charflag = 1;
        }

    }//GEN-LAST:event_jButtonMostrarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonDel;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonMostrar;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxPermissao;
    private javax.swing.JLabel jLabelPermissão;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanelBotoes;
    private javax.swing.JPanel jPanelFormulario;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePesquisaUsuario;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}

