/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visão;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.util.HashMap;
import javax.swing.JOptionPane;
import modeloConnectionX.ConectaBDX;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author danie
 */
public class Relatorios extends javax.swing.JFrame {
String permissao;
        String nome;
        String user;
    ConectaBDX conexaoBD = new ConectaBDX();
    
    public Relatorios() {
        initComponents();
        jButtonRelCliente.setBackground(new Color(0,0,0,0));
        jButtonRelEstoque.setBackground(new Color(0,0,0,0));
        jButtonRelFunc.setBackground(new Color(0,0,0,0));
        jButtonRelVendas.setBackground(new Color(0,0,0,0));
        jButtonSair.setBackground(new Color(0,0,0,0));
        
        
        URL url = this.getClass().getResource("/imagens/logoSafNormal.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(iconeTitulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonRelFunc = new javax.swing.JButton();
        jButtonRelEstoque = new javax.swing.JButton();
        jButtonRelCliente = new javax.swing.JButton();
        jButtonRelVendas = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Geração de Relatórios");
        setMinimumSize(new java.awt.Dimension(1050, 610));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1050, 610));
        setSize(new java.awt.Dimension(1050, 610));
        getContentPane().setLayout(null);

        jButtonRelFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botoes/relatorio.png"))); // NOI18N
        jButtonRelFunc.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botoes/relatorio linha.png"))); // NOI18N
        jButtonRelFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelFuncActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRelFunc);
        jButtonRelFunc.setBounds(170, 480, 160, 30);

        jButtonRelEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botoes/relatorio.png"))); // NOI18N
        jButtonRelEstoque.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botoes/relatorio linha.png"))); // NOI18N
        jButtonRelEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelEstoqueActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRelEstoque);
        jButtonRelEstoque.setBounds(750, 480, 140, 33);

        jButtonRelCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botoes/relatorio.png"))); // NOI18N
        jButtonRelCliente.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botoes/relatorio linha.png"))); // NOI18N
        jButtonRelCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRelCliente);
        jButtonRelCliente.setBounds(100, 230, 270, 33);

        jButtonRelVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botoes/relatorio.png"))); // NOI18N
        jButtonRelVendas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botoes/relatorio linha.png"))); // NOI18N
        jButtonRelVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelVendasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRelVendas);
        jButtonRelVendas.setBounds(730, 230, 160, 33);

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botoes/Botao Minimizar.png"))); // NOI18N
        jButtonSair.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botoes/Botao Minimizar Alterado.png"))); // NOI18N
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(963, 30, 40, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/telaRelatório.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1050, 610);

        setLocation(new java.awt.Point(280, 90));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRelVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelVendasActionPerformed
        try{
            conexaoBD.conectaBD();
            conexaoBD.executaSql("SELECT nomeproduto, valortotal, quantidade, nomecliente, nomemedico, datavenda, categoria, receita FROM vendas");
            
            JRResultSetDataSource relatResult = new JRResultSetDataSource(conexaoBD.rs);
            JasperPrint jpPrint = JasperFillManager.fillReport("G:/Sistema de Administração de Farmácia/Relatorios/vendas.jasper/", new HashMap(), relatResult);
            JasperViewer jv = new JasperViewer (jpPrint, false);
            jv.setVisible(true);
            conexaoBD.desconectaBD();
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null,"Não foi possivel abrir o formulario" + ex);
        }
    }//GEN-LAST:event_jButtonRelVendasActionPerformed

    private void jButtonRelFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelFuncActionPerformed
        try{
            conexaoBD.conectaBD();
            conexaoBD.executaSql("SELECT Cod_func, nomefunc, cargo, telefone, CPF FROM funcionarios");
            
            JRResultSetDataSource relatResult = new JRResultSetDataSource(conexaoBD.rs);
            JasperPrint jpPrint = JasperFillManager.fillReport("G:/Sistema de Administração de Farmácia/Relatorios/funcionario.jasper/", new HashMap(), relatResult);
            JasperViewer jv = new JasperViewer (jpPrint, false);
            jv.setVisible(true);
            conexaoBD.desconectaBD();
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null,"Não foi possivel abrir o formulario" + ex);
        }
    }//GEN-LAST:event_jButtonRelFuncActionPerformed

    private void jButtonRelClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelClienteActionPerformed
        try{
            conexaoBD.conectaBD();
            conexaoBD.executaSql("SELECT nome_cliente, cpf_cliente, email_cliente, tel_cliente FROM clientes");
            
            JRResultSetDataSource relatResult = new JRResultSetDataSource(conexaoBD.rs);
            JasperPrint jpPrint = JasperFillManager.fillReport("G:/Sistema de Administração de Farmácia/Relatorios/cliente.jasper/", new HashMap(), relatResult);
            JasperViewer jv = new JasperViewer (jpPrint, false);
            jv.setVisible(true);
            conexaoBD.desconectaBD();
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null,"Não foi possivel abrir o formulario" + ex);
        }
    }//GEN-LAST:event_jButtonRelClienteActionPerformed

    private void jButtonRelEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelEstoqueActionPerformed
        try{
            conexaoBD.conectaBD();
            conexaoBD.executaSql("SELECT nomeproduto, valorcompra, valorvenda, quantidade, fornecedor, categoria, receita FROM estoque");
            
            JRResultSetDataSource relatResult = new JRResultSetDataSource(conexaoBD.rs);
            JasperPrint jpPrint = JasperFillManager.fillReport("G:/Sistema de Administração de Farmácia/Relatorios/estoque2.jasper/", new HashMap(), relatResult);
            JasperViewer jv = new JasperViewer (jpPrint, false);
            jv.setVisible(true);
            conexaoBD.desconectaBD();
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null,"Não foi possivel abrir o formulario" + ex);
        }
    }//GEN-LAST:event_jButtonRelEstoqueActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Relatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Relatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Relatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Relatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Relatorios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRelCliente;
    private javax.swing.JButton jButtonRelEstoque;
    private javax.swing.JButton jButtonRelFunc;
    private javax.swing.JButton jButtonRelVendas;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
