/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visão;

import controleX.CriptografaSenha;
import java.awt.Color;
import java.awt.Event;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import modeloConnectionX.ConectaBDX;

/**
 *
 * @author Filipe
 */
public class TelaLogin extends javax.swing.JFrame {
    /**
     * Creates new form TelaLogin
     */
    CriptografaSenha criptografaSenha = new CriptografaSenha();
    ConectaBDX conectaBD = new ConectaBDX();
    RecuperacaoSenha recuperacaoSenha = new RecuperacaoSenha();
    
    public TelaLogin() {
        initComponents();
        jButtonEsqueciASenha.setVisible(false);
        
        setBackground(new Color(0, 0, 0, 0));
        jTextFieldUsuario.setBackground(new Color(0, 0, 0, 0));
        jPasswordFieldSenha.setBackground(new Color(0, 0, 0, 0));
        jButtonAcessar.setBackground(new Color(0, 0, 0, 0));
        jButtonSair.setBackground(new Color(0, 0, 0, 0));
        jButtonMinimizar.setBackground(new Color(0, 0, 0, 0));
        
        URL url = this.getClass().getResource("/imagens/logoSafNormal.png");  
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url); 
        this.setIconImage(iconeTitulo);
        jTextFieldUsuario.requestFocus();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        teste = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jButtonEsqueciASenha = new javax.swing.JButton();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jButtonAcessar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jButtonMinimizar = new javax.swing.JButton();
        jLabelBackgroun = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela de Login");
        setUndecorated(true);
        getContentPane().setLayout(null);

        teste.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Gif-Logo-SAF.gif"))); // NOI18N
        teste.setFocusable(false);
        getContentPane().add(teste);
        teste.setBounds(120, 80, 340, 290);

        jTextFieldUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldUsuario.setToolTipText("Usuário");
        jTextFieldUsuario.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextFieldUsuario.setDragEnabled(true);
        jTextFieldUsuario.setMinimumSize(new java.awt.Dimension(0, 14));
        jTextFieldUsuario.setName("Usuário"); // NOI18N
        jTextFieldUsuario.setOpaque(false);
        jTextFieldUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldUsuarioFocusLost(evt);
            }
        });
        jTextFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldUsuario);
        jTextFieldUsuario.setBounds(505, 240, 265, 30);

        jButtonEsqueciASenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botoes/esqueceu senha normal.png"))); // NOI18N
        jButtonEsqueciASenha.setToolTipText("");
        jButtonEsqueciASenha.setContentAreaFilled(false);
        jButtonEsqueciASenha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEsqueciASenha.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botoes/esqueceu senha.png"))); // NOI18N
        jButtonEsqueciASenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEsqueciASenhaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEsqueciASenha);
        jButtonEsqueciASenha.setBounds(670, 360, 100, 20);

        jPasswordFieldSenha.setToolTipText("Senha");
        jPasswordFieldSenha.setBorder(null);
        jPasswordFieldSenha.setOpaque(false);
        jPasswordFieldSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFieldSenhaFocusGained(evt);
            }
        });
        jPasswordFieldSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldSenhaActionPerformed(evt);
            }
        });
        jPasswordFieldSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordFieldSenhaKeyPressed(evt);
            }
        });
        getContentPane().add(jPasswordFieldSenha);
        jPasswordFieldSenha.setBounds(505, 320, 265, 30);

        jButtonAcessar.setFont(new java.awt.Font("Gilroy Light", 0, 14)); // NOI18N
        jButtonAcessar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botoes/Botao Entrar Normal.png"))); // NOI18N
        jButtonAcessar.setBorder(null);
        jButtonAcessar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAcessar.setOpaque(false);
        jButtonAcessar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botoes/botaoEntrar.png"))); // NOI18N
        jButtonAcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcessarActionPerformed(evt);
            }
        });
        jButtonAcessar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonAcessarKeyPressed(evt);
            }
        });
        getContentPane().add(jButtonAcessar);
        jButtonAcessar.setBounds(500, 390, 90, 30);

        jButtonSair.setFont(new java.awt.Font("Gilroy Light", 0, 12)); // NOI18N
        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botoes/Botao Fechar.png"))); // NOI18N
        jButtonSair.setBorder(null);
        jButtonSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSair.setFocusable(false);
        jButtonSair.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botoes/Botao Fechar alterado.png"))); // NOI18N
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(950, 20, 30, 30);

        jButtonMinimizar.setFont(new java.awt.Font("Gilroy Light", 0, 12)); // NOI18N
        jButtonMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botoes/Botao Minimizar.png"))); // NOI18N
        jButtonMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMinimizar.setFocusable(false);
        jButtonMinimizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botoes/Botao Minimizar Alterado.png"))); // NOI18N
        jButtonMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinimizarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMinimizar);
        jButtonMinimizar.setBounds(920, 20, 30, 30);

        jLabelBackgroun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/backgrundSAF.png"))); // NOI18N
        jLabelBackgroun.setFocusable(false);
        getContentPane().add(jLabelBackgroun);
        jLabelBackgroun.setBounds(0, 0, 993, 562);

        setSize(new java.awt.Dimension(992, 562));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordFieldSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldSenhaActionPerformed

    private void jButtonAcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcessarActionPerformed
        
        if(jTextFieldUsuario.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Por favor, insira o login.", "Atenção!", 2);
        }
        else if(jPasswordFieldSenha.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Por favor, insira a senha.", "Atenção!", 2);
        }
        else{
            String senha = jPasswordFieldSenha.getText();
            criptografaSenha.setSenha(senha);
            String senhaCriptografada = criptografaSenha.getSenha();
            
            conectaBD.conectaBD();
            conectaBD.executaSql("select nomefunc, usuario, senha, cargo from funcionarios where usuario='"+jTextFieldUsuario.getText()+"' and senha='" +senhaCriptografada+ "'");
            
            try {
                conectaBD.rs.first();
                if(conectaBD.rs.getString("usuario").equals(jTextFieldUsuario.getText()) && conectaBD.rs.getString("senha").equals(senhaCriptografada)){
                    String user = conectaBD.rs.getString("usuario");
                    String permissao = conectaBD.rs.getString("cargo");
                    String nome = conectaBD.rs.getString("nomefunc");
                    TelaPrincipal telaPrincipal = new TelaPrincipal(user, permissao, nome);
                    telaPrincipal.setVisible(true);
                    dispose();
                    conectaBD.desconectaBD();
                }
                else {
                    JOptionPane.showMessageDialog(null, "Usuario ou senha incorretos");
                    jTextFieldUsuario.setText("");
                    jPasswordFieldSenha.setText("");
                    jTextFieldUsuario.requestFocus();
                }
            } 
            catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Usuario ou senha incorretos");
                    jTextFieldUsuario.setText("");
                    jPasswordFieldSenha.setText("");
                    jTextFieldUsuario.requestFocus();
            }
        }
    }//GEN-LAST:event_jButtonAcessarActionPerformed

    private void jPasswordFieldSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldSenhaFocusGained
        getRootPane().setDefaultButton(jButtonAcessar);
    }//GEN-LAST:event_jPasswordFieldSenhaFocusGained

    private void jTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsuarioActionPerformed

    private void jTextFieldUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioFocusLost

    }//GEN-LAST:event_jTextFieldUsuarioFocusLost

    private void jTextFieldUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioFocusGained
        
    }//GEN-LAST:event_jTextFieldUsuarioFocusGained

    private void jButtonEsqueciASenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEsqueciASenhaActionPerformed
        recuperacaoSenha.show();
        this.dispose();
    }//GEN-LAST:event_jButtonEsqueciASenhaActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinimizarActionPerformed
        // TODO add your handling code here:
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jButtonMinimizarActionPerformed

    private void jButtonAcessarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonAcessarKeyPressed
        
        if(evt.getKeyCode() == Event.ENTER){
		jButtonAcessar.doClick();
	}
        
    }//GEN-LAST:event_jButtonAcessarKeyPressed

    private void jPasswordFieldSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldSenhaKeyPressed
        if(evt.getKeyCode() == Event.ENTER){
		jButtonAcessar.doClick();
	}
    }//GEN-LAST:event_jPasswordFieldSenhaKeyPressed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAcessar;
    private javax.swing.JButton jButtonEsqueciASenha;
    private javax.swing.JButton jButtonMinimizar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabelBackgroun;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JTextField jTextFieldUsuario;
    private javax.swing.JLabel teste;
    // End of variables declaration//GEN-END:variables
}
